# Generated by Django 5.2.1 on 2025-05-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_title', models.CharField(max_length=500)),
                ('About_image', models.ImageField(upload_to='product/')),
                ('About_subtext', models.CharField(max_length=500)),
                ('About_more', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_image', models.ImageField(upload_to='product/')),
                ('Blog_title', models.CharField(max_length=500)),
                ('Blog_subtext', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Design_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='Design_subtext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtext', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(max_length=100)),
                ('hero_subtitle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='product/')),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_image', models.ImageField(upload_to='product/')),
                ('Service_name', models.CharField(max_length=200)),
                ('Service_subtitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('text', models.TextField()),
            ],
        ),
    ]
